objects/Beer__c.object
<CustomObject>
    <fields>
        <fullName>Alcohol__c</fullName>
        <label>Alcohol %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Remaining_Quantity__c</fullName>
        <label>Remaining Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <label>Tags</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <label>Total Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>brewery_Name__c</fullName>
        <label>Brewery Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BeerSearchAuraService.cls
public class BeerSearchAuraService {
    @AuraEnabled
    public static List<Beer__c> searchBeer(String searchParam){
        String query='';
        if(searchParam <> null){
        string likeParam= '%'+searchParam+'%';
        query='Select Name,brewery_Name__c,Price__c,Alcohol__c,Remaining_Quantity__c,Total_Quantity__c,Tags__c from Beer__c where Name like :likeParam limit 30';    
        }else{
        query='Select Name,brewery_Name__c,Price__c,Alcohol__c,Remaining_Quantity__c,Total_Quantity__c,Tags__c from Beer__c limit 30';        
        }
        List<sObject> beerList = Database.query(query);
        return beerList;
    }
}